[Service]
  Host = "localhost"
  Port = 49991
  ConnectRetries = 3
  HealthCheck = ""
  StartupMsg = "device BME680 started"
  ReadMaxLimit = 256
  Timeout = 5000

[Clients]
  [Clients.Data]
    Host = "localhost"
    Port = 48080

  [Clients.Metadata]
    Host = "localhost"
    Port = 48081

[Device]
  DataTransform = true
  Discovery = false
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
  RemoteURL = ""
  File = "./device-bme680.log"

[[Schedules]]
  Name = "Schedule_bme680"
  Frequency = "PT2S"

[[ScheduleEvents]]
  Name = "Temperature"
  Schedule = "Schedule_bme680"
  Path = "/api/v1/device/all/Get_Temperature"

[[ScheduleEvents]]
  Name = "Humidity"
  Schedule = "Schedule_bme680"
  Path = "/api/v1/device/all/Get_Humidity"

[[ScheduleEvents]]
  Name = "Pressure"
  Schedule = "Schedule_bme680"
  Path = "/api/v1/device/all/Get_Pressure"

[[DeviceList]]
  Name = "BME680Device"
  Profile = "BME680_Device"
  Description = "Digital 4-in-1 sensor with gas, humidity, pressure and temperature measurement"
  Labels = [ "Temperature, Humidity, Pressure, Gas" ]
  [DeviceList.Addressable]
    Address = "/api/v1/device/BME680Device"

